### Generare automata a functiei $$\phi$$ descrisa in curs pe care el o scoate de nicaieri

In [28]:
d = 3 
n = 4
q = 3
Amin = [frozenset([1, 2, 3]), frozenset([1, 2, 4]), frozenset([3, 4])]

In [29]:
from itertools import chain, combinations

def powerset(iterable):
  xs = list(iterable)
  # note we return an iterator rather than a list
  return chain.from_iterable( combinations(xs,n) for n in range(len(xs)+1) )

In [30]:
# Vedem daca o multime e autorizata sau nu
def isAuthorized(candidate, Amin):
    for allowed in Amin:
        if len(allowed.difference(candidate)) == 0:
            return True
    return False

# Cautam toate multimile MAXIMAL NEAUTORIZATE.
NAmax = []
for candidate in powerset(range(1, n + 1)):
    # E maximal neautroizata daca orice element adaugam devine autorizata
    ok = True
    c = frozenset(candidate)
    if isAuthorized(c, Amin):
        continue
    for element in range(1, n + 1):
        if element in c:
              continue
        aux = list(c)
        aux.append(element)
        added = frozenset(aux)
        if not isAuthorized(added, Amin):
            ok = False
            break
    if ok == False:
        continue
    NAmax.append(c)
print("Multimile maximal neautorizate sunt:")
for i in NAmax:
    print(list(i))

Multimile maximal neautorizate sunt:
[1, 2]
[1, 3]
[1, 4]
[2, 3]
[2, 4]


In [44]:
# Cautam sa face un sistem 
# Brute force maxim ^^
# Scoatem o lista de solutii care pot fi

from itertools import product, combinations
import numpy as np

aux = np.array([0] * d)
aux[0] = 1
e = np.matrix(aux).transpose()

def hasSolution(ma, givesol = False):
    for c in product([-1, 0, 1], repeat = len(indexes)):
        cn = np.matrix([c]).transpose()
        x = np.count_nonzero(abs((((ma * cn) % q) - e)))
        if x == 0:
            if givesol == True:
                return cn
            return True
    return False

# Cate solutii vrem sa determinam
SOLS = 1

# Incercam sa avem vectori doar cu 1, 0, si -1 ca si componente.
all_vectors = list(product([1, 0, -1], repeat = d))
for solution in combinations(all_vectors, n):
    m = np.matrix(list(solution)).transpose()
    ok = True
    for A in Amin:
        indexes = list(np.array(sorted(list(A))) - 1)
        ma = m[:, indexes]
        if hasSolution(ma) == False:
            ok = False
            break
    if ok == False:
        continue
    for A in NAmax:
        indexes = list(np.array(sorted(list(A))) - 1)
        ma = m[:, indexes]
        if hasSolution(ma) == True:
            ok = False
            break
    if ok == False:
        continue
    print(m)
    print("Solutiile pentru baza")
    for A in Amin:
        indexes = list(np.array(sorted(list(A))) - 1)
        ma = m[:, indexes]
        x = hasSolution(ma, True)
        print(A)
        print("Combinatia lineara este \n",x)
        print("Print solutia da vectorul \n", ma * x)
        print("Care modulo q este: \n", (ma * x) % q)
    print("Alta posibila solutie")
    SOLS -= 1
    if SOLS == 0:
        break
print("DONE")
# Construim matricea sistemului

[[ 1  1  1  1]
 [ 1  1  0  0]
 [ 1  0  1 -1]]
Solutiile pentru baza
frozenset({1, 2, 3})
Combinatia lineara este 
 [[-1]
 [ 1]
 [ 1]]
Print solutia da vectorul 
 [[1]
 [0]
 [0]]
Care modulo q este: 
 [[1]
 [0]
 [0]]
frozenset({1, 2, 4})
Combinatia lineara este 
 [[ 1]
 [-1]
 [ 1]]
Print solutia da vectorul 
 [[1]
 [0]
 [0]]
Care modulo q este: 
 [[1]
 [0]
 [0]]
frozenset({3, 4})
Combinatia lineara este 
 [[-1]
 [-1]]
Print solutia da vectorul 
 [[-2]
 [ 0]
 [ 0]]
Care modulo q este: 
 [[1]
 [0]
 [0]]
Alta posibila solutie
DONE
